### ISSUE TITLE
Some changes 3

### ISSUE THREAD

**Issue by wifiextender** [woodruffw/screenfetch-c#13]
Hello William,

I have added internationalization.

Wrote argument parsing module based on argp.h

Wrote m4 (macro processor) files that will
be used to test for the presence of X11 and OpenGL
headers, they won't produce any errors if the current
operating system lacks these headers, instead no
-lX11 -lGL linker flags will be substituted. It took
me half day to find the needed information in `info m4'
but it is neat feature as it enables you to add support
for NVIDIA and INTEL gpu's, perharps you should add support
for those manufactors as well and substitute some macros,
pass them to AM_CPPFLAGS, and in detect.c module
you may use:

if (AMD_RADEON)  | amd macro 
    ...
else if (NVIDIA) | nvidia macro 
    ...
else if (INTEL)  | intel macro 
    ...
else
     fallback to the bash scripts

Your old makefile and the test files in test
folder was removed.

Copied `bootstrap' script (from my pdf2img-c)
that will produce the needed
configuration files, but it needs further polishing.
Whenever you want to add platform specific linker
flags or macros you may prefer to put them with
bash variable, see `bootstrap' -
'${prog_name}'_LDADD  and  AM_CPPFLAGS

po/en_GB.po contains only testing strings,
so I could verify that the internationalization
is working flawlessly.

What is missing:  `uname' (linux/mac) tests,
`machine' (*bsd) tests, the detect scripts
should be moved by Makefile.am (find out how),
po/en_GB.po should contain all strings that will be
translated, so everyone will be able to copy it,
rename it and translate all 'msgstr'. Open up
`bootstrap' and do the described tasks in the comments.

Drop the windows support, and create other screenfetch
written in C sharp as the language provideds hardware
support out of the box and it will be relatively easy
to implement all current features within 300 lines
or less.

The performance was also improved.

GitHub doesn't lets me to propose a new pull request as my
screenfetch-c fork is several commits behind the master
branch and the git client on my tablet isn't helping me
either, so my hands are tied.
Can you copy all files from my screenfetch-c fork and
push them to the master branch ?

I have tried to keep this comment as shorter as possible
without describing what else was edited.

Best regards,
Aaron Caffrey

**Comment by woodruffw** [comment]
Thanks Aaron.

Don't worry about the pull request - I can see the commits you make on your master branch and pull them in manually. I haven't completely merged your previous changes yet (they're pretty significant), so wait a few days on this one.

Best,
William
