### ISSUE TITLE
build fails on OSX 10.10

### ISSUE THREAD

**Issue by skyhighwings** [woodruffw/screenfetch-c#15]
https://gist.github.com/anonymous/950fae6c547aaa7db603
https://gist.github.com/anonymous/cf1a4989d76eee8bee07

Anything else I can get to help fix this?

**Comment by woodruffw** [comment]
Hi,

I hadn't updated the Homebrew formula for a while, and it was pretty out-of-sync with the actual source tree.
I've updated it to the latest screenfetch-c version (1.4.1), so try running `brew update` and fetching the latest formula down. Then, just `brew install` it like last time.

This formula builds for me on OS X 10.6.8, which is the latest version my hardware allows to test on.

If any errors (or warnings) show up during compilation again, please link them here.

Thank you,
William

**Comment by skyhighwings** [comment]
The same errors occurred (precisely the same). I've gone ahead and
created #16 for your review. Thanks for the program!

On 3/21/2015 11:13 AM, William Woodruff wrote:
> Hi,
> 
> I hadn't updated the Homebrew formula for a while, and it was pretty
> out-of-sync with the actual source tree.
> I've updated it to the latest screenfetch-c version (1.4.1), so try
> running |brew update| and fetching the latest formula down. Then, just
> |brew install| it like last time.
> 
> This formula builds for me on OS X 10.6.8, which is the latest version
> my hardware allows to test on.
> 
> If any errors (or warnings) show up during compilation again, please
> link them here.
> 
> Thank you,
> William
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woodruffw/screenfetch-c/issues/15#issuecomment-84381402>.
> 

-- 
Rylee Fowler
PGP: 41EA 1D94 F261 8602 6CD4 B2B5 05A6 3421 F637 E333
Never heard of PGP? See https://emailselfdefense.fsf.org/en/ !
https://keybase.io/rylee
