### ISSUE TITLE
user@host is misaligned

### ISSUE THREAD

**Issue by jamesrobb** [woodruffw/screenfetch-c#18]
Hello,

I have managed to modify the source code so that way the colours are the ones I would like, but I haven't seen where in the code I can fix the alignment issue with the user@host part of the displayed output. Attached is an image of what I mean.

Can someone be of help in letting me know how I can fix this?

http://imgur.com/qPFFVuC

**Comment by woodruffw** [comment]
Hi @jamesrobb,

Looks like there's an extra space in the Ubuntu logo (`logos.c#107`):

```diff
diff --git a/src/logos.c b/src/logos.c
index 38f8c36..9f5fce9 100644
--- a/src/logos.c
+++ b/src/logos.c
@@ -104,7 +104,7 @@ char *lmde_logo[] =
 /* 18 */
 char *ubuntu_logo[] =
 {
-	""TLRD"                          ./+o+-       " TNRM,
+	""TLRD"                          ./+o+-      " TNRM,
 	""TWHT"                  yyyyy- "TLRD"-yyyyyy+     " TNRM,
 	""TWHT"               "TWHT"://+//////"TLRD"-yyyyyyo     " TNRM,
 	""TYLW"           .++ "TWHT".:/++++++/-"TLRD".+sss/`     " TNRM,
```

I'll be fixing it on the master branch in a few seconds - thanks for finding it!

**Comment by jamesrobb** [comment]
Thanks!
