### ISSUE TITLE
Failed to detect the Distro, WM.

### ISSUE THREAD

**Issue by bdt0-rocklee** [woodruffw/screenfetch-c#19]
![2015-10-27-174640_784x87_scrot](https://cloud.githubusercontent.com/assets/8173131/10768352/9d4dce40-7d06-11e5-9655-6f645c3dc4c7.png)

The particular problem is faced in Slackware, herbstluftwm was the WM used here.  It would be nice if the software recognizes the WM and ignores the DE if only WM is installed. The slackware Ascii art is found in the original screenfetch.
Thank you. :smile:

**Comment by woodruffw** [comment]
Could you tell me the contents of `/etc/os-release`?
Additionally, please look for a file named `/etc/slackware-release` or something similar (most likely in `/etc`). Using that for detecting slackware would be ideal.

Does screenfetch-c report herbstluftwm correctly?

**Comment by bdt0-rocklee** [comment]
Contents of /etc/os-release[image attached].
![2015-10-28-135139_461x121_scrot](https://cloud.githubusercontent.com/assets/8173131/10790461/71f5f224-7da9-11e5-87a5-9e2414c69c2f.png)
 The Slackware version is found in a file name /etc/slackware-version. 

2) Does screenfetch-c report herbstluftwm correctly?
No. It doesn't.

**Comment by woodruffw** [comment]
d196e6c2b02d234a452ee7523094dc5f06dfc4de should fix the detection of Slackware. 

> 2) Does screenfetch-c report herbstluftwm correctly?
> No. It doesn't.

Does it report anything at all? If not, what error message does it produce?

**Comment by woodruffw** [comment]
It looks like herbstluftwm expects the user to set the value of the `_NET_WM_NAME` property manually.

https://github.com/herbstluftwm/herbstluftwm/blob/0c26a29512e311e81b74c6dae34a23bd2a892679/src/ewmh.cpp#L155:

```c++
void ewmh_update_wmname() {
    ewmh_set_wmname(settings_find_string("wmname"));
}
```

Setting the `wmname` property in herbstluftwm's configuration file to "herbstluftwm" (or whatever you want your WM to be called) should fix it. IIRC, XMonad has/had a similar problem with screenfetch-c.

**Comment by woodruffw** [comment]
Closing #19 (can be fixed in WM's configuration).
