### ISSUE TITLE
Manpage issue

### ISSUE THREAD

**Issue by m-wells** [woodruffw/screenfetch-c#21]
I believe that the
`man/screenfetch-c.1`
should be
`man/man1/screenfetch-c.1`

then in my `.bashrc` I can properly setup
`MANPATH=:~/builds/screenfetch-c/man`
and have `man screenfetch-c` work correctly

**Comment by woodruffw** [comment]
Yep, that's correct. I'll fix this in a moment.

**Comment by woodruffw** [comment]
Release 1.4.4 contains the changes.
