### ISSUE TITLE
MinGW compatibility

### ISSUE THREAD

**Issue by darealshinji** [woodruffw/screenfetch-c#23]
It would be nice if screenfetch-c was full functional as a standalone program in cmd.exe when built with the MinGW compilers.
It can already be build with MinGW if you add ` -lws2_32` to the LDFLAGS but the output in `cmd.exe` is obviously a mess since the Unix specific features are missing and the bash color flags are ignored.

**Comment by woodruffw** [comment]
Thanks for bringing this to my attention! It's interesting that screenfetch-c builds at all with MinGW - I would have guessed that at least *some* of the external functions I used via cygwin would be undefined.

Unfortunately, I no longer develop actively on Windows, so I'm not sure if this is something that I will ever personally work on. screenfetch-c is mostly in maintenance mode - I haven't added any significant features to it in the last year or two.

That being said, I'm more than happy to review and merge any commits you have towards this goal. I'm not sure what `conhost` uses for console colors (I thought it used ANSI codes like the ones screenfetch-c emits), but that should be a pretty quick fix. Similarly, the simplest way to circumvent the missing unix/POSIX functions is probably to create a new *src/plat/mingw* subdirectory and corresponding `make` target.

**Comment by darealshinji** [comment]
Detects DE as Metro. Tested on Msys2.
But now I've spotted something else: Kernel is detected as `Windows NT 10.0` but OS is `Microsoft Windows 7`, should be Windows 10 though.

**Comment by darealshinji** [comment]
Closing this issue.

I may open a pull request later to add information to the README on how to use a MinGW build with Batch and PowerShell scripts.
