### ISSUE TITLE
Modern logo for Windows 8 and 10

### ISSUE THREAD

**Issue by darealshinji** [woodruffw/screenfetch-c#33]
Windows 8, 8.1 and 10 should use the modern logo, like in the shell script version of screenFetch.

**Comment by woodruffw** [comment]
Definitely. I don't remember where I got most of the original logos from, but using KittyKatt's with a GPLv3 notice in the LICENSE should be fine.

**Comment by darealshinji** [comment]
The Modern Windows logo was originally submitted by me: https://github.com/KittyKatt/screenFetch/commit/8d962abe4bd15ec86840c3f1daddbf56d8f8ae6d
So, if I say you can add it under the MIT license I guess that should be fine (?).

**Comment by woodruffw** [comment]
Yeah, that should be fine then. I'll commit it shortly.

**Comment by woodruffw** [comment]
Included it in b7eb30d. I'll close this issue once you confirm things are working smoothly.

**Comment by darealshinji** [comment]
Works. But now it shows `Font: Unknown`. Is there even a detection method for "Font" in detect.c?

**Comment by woodruffw** [comment]
On Windows, only for Cygwin (see the poorly named `detect_gtk` function).

Font detection on Linux was actually broken because of a clobbered variable until 4a9a61e. It's still not very reliable, though.

**Comment by darealshinji** [comment]
Okay then. I'll close this issue.
