### ISSUE TITLE
Don't throw errors

### ISSUE THREAD

**Issue by DmitryHetman** [woodruffw/screenfetch-c#37]
[[ ! ]] Error: No desktop environment found. (src/plat/linux/detect.c:662)
[[ ! ]] Error: No _NET_WM_NAME property found. (src/plat/linux/detect.c:699)

**Comment by woodruffw** [comment]
Screenfetch-c prints those upon detection failure. You can hide them with `-E`/`--suppress-errors`.

**Comment by woodruffw** [comment]
`man screenfetch-c` documents all options, by the way.
