### ISSUE TITLE
overflow in memory detection

### ISSUE THREAD

**Issue by zzxyz** [woodruffw/screenfetch-c#40]
![image](https://user-images.githubusercontent.com/20363998/32673283-6d3f44ac-c603-11e7-9d36-94332a9c7993.png)

igc@thor:screenfetch-c$ prtdiag | grep -i 'memory'
Memory size: 130848 Megabytes
======================= Physical Memory Configuration ========================
igc@thor:screenfetch-c$ screenfetch-c
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM igc@thor
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM██MMMM$MMMMMMMMMMMM OS: SunOS
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM█MMMM██MMMM█MMMMMMMMMMMM Kernel: 5.11
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM████████████MMMMMMMMMMMM CPU:     UltraSPARC-T2+ (chipid 65552, clock 1415 MHz)
        MMMMMMMMMMMMMMMMMMMMMMMMMM██M██████████████MM█MMMMMMMMM GPU: Unknown
        MMMMMMMMMMMMMMMMMMMMMMMMMMM████████████████████MMMMMMMM Shell: bash version 4.3.33(1)
        MMMMMMMMMMMMMMMMMMMMMMMMMMM███████████████████MMMMMNMMM Packages: 942
        MMMMMMMMMMMMMMMMMMMMM██████████████████████████████MMMM Disk: 2G / 3G (66%)
        MMMMMMMMMMMMMMMMMMMMMMMM█████████████████████████MMMMMM Memory: -224MB
        ======================================================= Uptime: 69d 22h 17m 27s
        MMM###NMMMMM####MMMM##MMMMMM####MMMMM#####MM##MMMM###MM Resolution: 1600x1200
        MM##MMMMMM###MM###MM##MMMM##MMM##MMMM###MMMM##MM###MMMM DE: Gnome
        M##MMMMMMM##MMMM##MM##MMMMMMMMMM##MMM##MMMMM##MM##MMMMM WM: Metacity
        MM####MMM###MMMM##MM##MMMMM#######MMM##MMMMM##MMM####MM WM Theme: Unknown
        MMMMM###MM##MMMM##MM##MMMM##MMMM##MMM##MMMMM##MMMMMN##M GTK: Not implemented
        MMMMMM##MM###MM###MM##MMMM##MMM###MMM##MMMMM##MMMMMM##M Icon Theme: Unknown
        M######MMMMM####MMMM=####MM#######MMM##MMMMM##MM#####MM Font: Unknown
        igc@thor:screenfetch-c$

igc@thor:screenfetch-c$

**Comment by zzxyz** [comment]
(overflow at a guess.  Perhaps the issue is something else.)

**Comment by zzxyz** [comment]
This fixes:
diff --git a/src/plat/sun/detect.c b/src/plat/sun/detect.c
index bf6fb24..79196c4 100644
--- a/src/plat/sun/detect.c
+++ b/src/plat/sun/detect.c
@@ -186,7 +186,7 @@ void detect_mem(void)
 {
        long long total_mem = 0;

-       total_mem = sysconf(_SC_PHYS_PAGES) * sysconf(_SC_PAGE_SIZE);
+       total_mem = (long long)sysconf(_SC_PHYS_PAGES) * (long long)sysconf(_SC_PAGE_SIZE);
        total_mem /= MB;

**Comment by woodruffw** [comment]
Thanks for debugging this. I'll fix it in a bit.
